# https://aka.ms/yaml

trigger:
- master

jobs:
- job: RunOnUbuntu16_04
  pool:
    vmImage: 'Ubuntu-16.04'
  
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y git cmake libmpfr-dev libboost1.58-dev
    displayName: 'Install dependencies'
  
  - script: cmake -H. -Bbuild
    displayName: 'Configure'
  
  - script: cmake --build build
    displayName: 'Build'
  
  - script: ./build/pi_day
    displayName: 'Run'

- job: RunOnUbuntu18_04Container
  pool:
    vmImage: 'Ubuntu-16.04'

  container: ubuntu:18.04
  
  steps:
  - script: |
      su -c 'apt-get update' </dev/null
      su -c 'apt-get install -y sudo' </dev/null
    displayName: 'Install sudo'
  
  - script: sudo apt-get install -y git cmake libmpfr-dev libboost1.62-dev
    displayName: 'Install dependencies'
  
  - script: cmake -H. -Bbuild
    displayName: 'Configure'
  
  - script: cmake --build build
    displayName: 'Build'
  
  - script: ./build/pi_day
    displayName: 'Run'
