# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'

jobs:
- job: RunOnUbuntu16_04
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y git cmake libmpfr-dev libboost1.58-dev
    displayName: 'Install dependencies'

  - script: cmake -H. -Bbuild
    displayName: 'Configure'

  - script: cmake --build build
    displayName: 'Build'

  - script: ./build/pi_day
    displayName: 'Run'
- job: RunOnClang8Container
  pool:
    vmImage: 'Ubuntu-16.04'

  container: prsam/pi-day:llvm8-stretch

  steps:
  - script: cmake -H. -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPI_DIGITS=1000000
    displayName: 'Configure'

  - script: cmake --build build
    displayName: 'Build'

  - script: ./build/pi_day
    displayName: 'Run'

- job: RunOnMacOS
  pool:
    vmImage: 'macOS-10.13'  # 'vs2017-win2016'

  steps:
  - script: |
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    displayName: 'Install Homebrew'

  - script: brew install mpfr boost
    displayName: 'Install dependencies'

  - script: cmake -H. -Bbuild
    displayName: 'Configure'

  - script: cmake --build build
    displayName: 'Build'

  - script: ./build/pi_day
    displayName: 'Run'

- job: RunOnWinVS17
  pool:
    vmImage: 'vs2017-win2016'

  container: prsam/pi-day:msvc-win1709

  steps:
  - script: cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -G"Visual Studio 15 2017 Win64"
    displayName: 'Configure'

  - script: cmake --build build --config Release
    displayName: 'Build'

  - script: .\build\Release\pi-day.exe
    displayName: 'Run'

