## References
# <https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema>
# <https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/?view=azure-devops>
# <https://docs.microsoft.com/en-us/azure/devops/pipelines/index?view=azure-devops>
#  List of Microsoft-hosted images
# <https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml>
# <https://aka.ms/yaml>

################################################################################
trigger:
  branches:
    include:
    - '*'

################################################################################
jobs:
- job: RunOnXenialVM
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y git cmake libmpfr-dev libboost1.58-dev
    displayName: 'Install dependencies'

  - script: cmake -H. -Bbuild
    displayName: 'Configure'

  - script: cmake --build build
    displayName: 'Build'

  - script: ./build/pi_day
    displayName: 'Run'
    
################################################################################
- job: RunOnClang8StretchContainer
  pool:
    vmImage: 'Ubuntu-16.04'

  container: prsam/pi-day:llvm8-stretch

  steps:
  - script: cmake -H. -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPI_DIGITS=1000000
    displayName: 'Configure'

  - script: cmake --build build
    displayName: 'Build'

  - script: ./build/pi_day
    displayName: 'Run'

################################################################################
- job: RunOnMacOSVM
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - script: |
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    displayName: 'Install Homebrew'

  - script: brew install mpfr boost
    displayName: 'Install dependencies'

  - script: cmake -H. -Bbuild
    displayName: 'Configure'

  - script: cmake --build build
    displayName: 'Build'

  - script: ./build/pi_day
    displayName: 'Run'

################################################################################
- job: RunOnWinVS17Container
  pool:
    vmImage: 'win1803'

  container: prsam/pi-day:msvc-win1803

  steps:
  - script: cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -G"Visual Studio 15 2017 Win64"
    displayName: 'Configure'

  - script: cmake --build build --config Release
    displayName: 'Build'

  - script: .\build\Release\pi-day.exe
    displayName: 'Run'

